version: "2.1"

executors:
  # `main` uses the `cimg/python:3.9.7` docker image
  main:
    docker:
      - image: cimg/python:3.9.7

jobs:

  # `deps` is used to check the python dependencies.
  deps:
    executor: main
    steps:
      - checkout
      - run: python --version
      - run: pipenv install

  # `test` is used to test the python package.
  test:
    executor: main
    steps:
      - checkout
      - run: python --version
      - run: pipenv install
      - run: pipenv install -e .
      - run: pipenv install flake8
      - run: pipenv run make flake8
      - run: pipenv run make test_python

  # `build` is used to build the distributable
  build:
    executor: main
    steps:
      - checkout
      - run: pipenv install build
      - run: pipenv run python -m build --wheel


workflows:
  version: 2
  main:
    jobs:
      - deps
      - test:
          requires:
            - deps
      - build:
          requires:
            - deps
